language: ruby

rvm:
   - 1.9.2
   - 1.9.3
   - 2.0.0
   - 2.1.0
   - 2.2.0
   - rbx-19mode
   - jruby-19mode

matrix:
   allow_failures:
      - rvm: rbx-18mode
      - rvm: rbx-19mode

bundler_args: "--without=development"
script: "bundle exec rspec spec"
sudo: false